version: '3'
services:
  linkedin.rails.postgres.db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  linkedin.rails.web:
    build: .
    command: bundle exec rails s -p 5000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "5000:5000"
    depends_on:
      - linkedin.rails.postgres.db
